name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'iac/**'  # Already handled by pulumi-deploy.yml
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  packages: write
  id-token: write  # Needed for Azure login

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.docker_tag.outputs.image_tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Docker image tag
        id: docker_tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "image_tag=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "Using Docker image tag: sha-${SHORT_SHA}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.docker_tag.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-azure:
    name: Deploy to Azure Web Apps
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
      # Using GitHub variables for web app names instead of Pulumi
      
      - name: Deploy to Frontend Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_FRONTEND_APP_NAME }}
          images: ghcr.io/${{ github.repository }}:${{ needs.build-and-push.outputs.image_tag }}
      
      - name: Deploy to Backend Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_BACKEND_APP_NAME }}
          images: ghcr.io/${{ github.repository }}:${{ needs.build-and-push.outputs.image_tag }}
      
      - name: Log out from Azure
        run: az logout
        if: always()
