name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'iac/**'  # Already handled by pulumi-deploy.yml
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  packages: write
  id-token: write  # Needed for Azure login

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-azure:
    name: Deploy to Azure Web Apps
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
      - name: Get resource names from Pulumi stack
        id: get-resources
        run: |
          # Install Pulumi CLI
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin
          
          # Configure Pulumi stack
          cd ./iac
          npm ci
          pulumi stack select dev
          
          # Get the web app names from Pulumi stack outputs
          FRONTEND_APP=$(pulumi stack output frontendUrl | sed 's/https:\/\///g' | sed 's/\.azurewebsites\.net//g')
          BACKEND_APP=$(pulumi stack output backendUrl | sed 's/https:\/\///g' | sed 's/\.azurewebsites\.net//g')
          
          echo "frontend_app=$FRONTEND_APP" >> $GITHUB_OUTPUT
          echo "backend_app=$BACKEND_APP" >> $GITHUB_OUTPUT
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Deploy to Frontend Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.get-resources.outputs.frontend_app }}
          images: ghcr.io/${{ github.repository }}:latest
      
      - name: Deploy to Backend Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.get-resources.outputs.backend_app }}
          images: ghcr.io/${{ github.repository }}:latest
      
      - name: Log out from Azure
        run: az logout
        if: always()
